package com.webApp.controllers;

public enum RequestOperationName {
    SET_QUESTION,
    SET_EXAMINEE,
    EXAMINEE_DATA_UPDATED,
    SET_EXAMINEE_EDUCATIONAL_DATA,
    EXAMINEE_EDUCATIONAL_DATA_UPDATED,
    SET_EXAMINEE_WORK_EXPERIENCE_DATA,
    EXAMINEE_WORK_EXPERIENCE_DATA_UPDATED,
    SET_JOB_ANSWERS,
    JOB_ANSWERS_UPDATED,
    SET_EXTRA_ANSWERS,
    EXTRA_ANSWERS_UPDATED,
    DELETE
}
